#define IDR_CONFERENCE_ENDED_TONE                      	4000
#define IDR_ENTRY_TONE                      			4001
#define IDR_EXIT_TONE                      				4002
#define IDR_INCOMING_CALL_TONE                      	4003
#define IDR_NEW_CHAT_TONE                      			4004
#define IDR_NEW_CHAT_TEXT_TONE                      	4005
#define IDR_NEW_PRIVATE_CHAT_TONE                      	4006
#define IDR_DIRECT_CALL_TONE                      	    4007
#define IDR_TEST_TONE                      	    		4008
