#ifndef APP_STRINGS_TABLE_H
#define APP_STRINGS_TABLE_H
ASCHAR *AppStringsTable[] =
{
	/* APP_STRINGS_CURL_ERROR_UNKNOWN */		ASTEXT("Unexpected code"),
	/* APP_STRINGS_CURL_ERROR_ACCESS_DENIED */		ASTEXT("Access Denied"),
	/* APP_STRINGS_CURL_ERROR_COULD_NOT_RESOLVE_PROXY */		ASTEXT("Could not resolve Web Proxy address"),
	/* APP_STRINGS_CURL_ERROR_COULD_NOT_RESOLVE_HOST */		ASTEXT("Could not resolve server address"),
	/* APP_STRINGS_CURL_ERROR_COULD_NOT_CONNECT */		ASTEXT("Connection failed"),
	/* APP_STRINGS_CURL_ERROR_HTTP_RETURNED_ERROR */		ASTEXT("Server returned error"),
	/* APP_STRINGS_CURL_ERROR_OPERATION_TIMED_OUT */		ASTEXT("Connection timed out"),
	/* APP_STRINGS_CURL_ERROR_GENERIC_SSL_FAILURE */		ASTEXT("Secured connection failed"),
	/* APP_STRINGS_CURL_ERROR_GOT_NOTHING */		ASTEXT("No response from server"),
	/* APP_STRINGS_CURL_ERROR_TOO_MANY_REDIRECTS */		ASTEXT("Unexpected redirection response"),
	/* APP_STRINGS_CURL_ERROR_BAD_CONTENT_ENCODING */		ASTEXT("Bad content encoding"),
	/* APP_STRINGS_CURL_ERROR_FILE_SIZE_EXCEEDED */		ASTEXT("File too large"),
	/* APP_STRINGS_ERROR_CONTACTING_VIDYO_PORTAL */		ASTEXT("Error contacting VidyoPortal"),
	/* APP_STRINGS_ERROR_SIGNIN */		ASTEXT("Invalid username or password"),
	/* APP_STRINGS_ICD_INVITE_TO_CONFERENCE */		ASTEXT("Invite to conference %s"),
	/* APP_STRINGS_ICD_NEW_CALL */		ASTEXT("New call from %s"),
	/* APP_STRINGS_REGISTER_LICENSE_NOT_AVAILABLE */		ASTEXT("Failed to register installation license with server. No licenses are currently available."),
	/* APP_STRINGS_SC_SERVER_CERTIFICATE_VERIFICATION_FAILED */		ASTEXT("Server certificate verification failed. Vidyo could not validate the server's identity and cannot securely connect. Would you like to connect insecurely?"),
	/* APP_STRINGS_CHANGES_TO_AUDIO_VIDEO_DEVICES */		ASTEXT("Some of the changes made will take effect on the next conference or call. "),
	/* APP_STRINGS_CANNOT_DETERMINE_LOG_PATH */		ASTEXT("Cannot determine path to write log file."),
	/* APP_STRINGS_CANNOT_DETERMINE_INSTALLED_PATH */		ASTEXT("Cannot determine path to language support files. Language will remain English."),
	/* APP_STRINGS_CANNOT_WRITE_LOG_FILE */		ASTEXT("Cannot write to log file."),
	/* APP_STRINGS_INIT_ERROR */		ASTEXT("Initialization error, code = %03d.  If the problem persists, please contact your support team."),
	/* APP_STRINGS_INIT_ERROR_VIDYO_SDK_BASE */		ASTEXT("VidyoDesktop could not start (%03d). If  the problem persists, please contact your support team. "),
	/* APP_STRINGS_INIT_ERROR_FRAMEWORK_LOG */		ASTEXT("VidyoDesktop could not start (%03d). If  the problem persists, please contact your support team. "),
	/* APP_STRINGS_INIT_ERROR_VIDYO_DESKTOP_LOG */		ASTEXT("VidyoDesktop could not start (%03d). If  the problem persists, please contact your support team. "),
	/* APP_STRINGS_INIT_ERROR_VIDYOPROXY_LOG */		ASTEXT("VidyoDesktop could not start (%03d). If  the problem persists, please contact your support team. "),
	/* APP_STRINGS_INIT_ERROR_SDK_CLIENT */		ASTEXT("VidyoDesktop could not start (%03d). Please make sure that your anti-virus or personal firewall is not blocking VidyoDesktop's operation. If the problem persists, please contact your support team. "),
	/* APP_STRINGS_INIT_ERROR_CONSTRUCTION_VD_LOGIC */		ASTEXT("VidyoDesktop could not start (%03d). If  the problem persists, please contact your support team. "),
	/* APP_STRINGS_INIT_ERROR_START_VD_LOGIC */		ASTEXT("VidyoDesktop could not start (%03d). If  the problem persists, please contact your support team. "),
	/* APP_STRINGS_INIT_ERROR_VD_HELPER_CONSTRUCT */		ASTEXT("VidyoDesktop could not start (%03d). If  the problem persists, please contact your support team. "),
	/* APP_STRINGS_INIT_ERROR_VD_HELPER_START */		ASTEXT("VidyoDesktop could not start (%03d). Please make sure that your anti-virus or personal firewall is not blocking VidyoDesktop's operation. If the problem persists, please contact your support team. "),
	/* APP_STRINGS_INIT_ERROR_CONSTRUCTION_STRING_TRANSLATION_TABLE */		ASTEXT("NA"),
	/* APP_STRINGS_INIT_ERROR_SSE2_CHECK_FAILED */		ASTEXT("This computer's CPU does not support the SSE2 instruction set required by VidyoDesktop to run. VidyoDesktop will exit."),
	/* APP_STRINGS_TASKBAR_ICON_ERROR */		ASTEXT("Error registering taskbar notification area icon. Application will exit."),
	/* APP_STRINGS_CONF_STATUS_HOTKEY */		ASTEXT("Hotkey for conference status window will not be active."),
	/* APP_STRINGS_AUDIO_DEBUG_HOTKEY */		ASTEXT("Hotkey for audio debug window will not be active."),
	/* APP_STRINGS_LOG_SETTINGS_HOTKEY */		ASTEXT("Hotkey for log settings dialog will not be active."),
	/* APP_STRINGS_APP_SERVER_COMM_ERROR */		ASTEXT("Error while communicating with VidyoPortal."),
	/* APP_STRINGS_PROTOCOL_VERSION_ERROR */		ASTEXT("Version of client incompatible with version of server. Please upgrade client by logging into VidyoPortal. Client will exit."),
	/* APP_STRINGS_INVALIDUSER_ERROR */		ASTEXT("User ID could not be registered with server. Please sign in again on VidyoPortal."),
	/* APP_STRINGS_INVALIDMAC_ERROR */		ASTEXT("MAC address of system needs to be registered with server."),
	/* APP_STRINGS_USERINCONF_ERROR */		ASTEXT("User already in conference."),
	/* APP_STRINGS_INVALIDCONF_ERROR */		ASTEXT("Conference not found. Please check the name and try to join again."),
	/* APP_STRINGS_MAXPORTS_ERROR */		ASTEXT("Port limit exceeded at server. Please try to join at a later time."),
	/* APP_STRINGS_LOCKEDCONF_ERROR */		ASTEXT("Conference locked."),
	/* APP_STRINGS_NOROUTER_ERROR */		ASTEXT("No router available. Please try to join at a later time."),
	/* APP_STRINGS_CONFMAXUSERS_ERROR */		ASTEXT("User limit exceeded for conference."),
	/* APP_STRINGS_OFFLINECALLER_ERROR */		ASTEXT("Must be online in order to make a call. Please sign in on VidyoPortal."),
	/* APP_STRINGS_OFFLINECALLEE_ERROR */		ASTEXT("The person you are trying to call is not online."),
	/* APP_STRINGS_INTERNAL_ERROR */		ASTEXT("An internal error has occurred. Please quit VidyoDesktop and sign in again to the VidyoPortal. If the problem persists, please contact your support team."),
	/* APP_STRINGS_START_VIDEO_INTERNAL_ERROR */		ASTEXT("Error trying to start the camera. Please verify that the camera is not being used by another application."),
	/* APP_STRINGS_START_AUDIO_INTERNAL_ERROR */		ASTEXT("Error trying to start the microphone. Please verify that the microphone is not being used by another application."),
	/* APP_STRINGS_CONTACT_USER_INTERNAL_ERROR */		ASTEXT("An internal error has occurred while contacting user. Please quit VidyoDesktop and sign in again to the VidyoPortal. If the problem persists, please contact your support team."),
	/* APP_STRINGS_USER_NO_ANSWER */		ASTEXT("User did not answer the call"),
	/* APP_STRINGS_ROUTER_REJECT_JOIN_ERROR */		ASTEXT("Request to join conference was rejected. Please try to join again."),
	/* APP_STRINGS_OTHER_PARTY_HANGUP */		ASTEXT("The other participant in the call has ended the call."),
	/* APP_STRINGS_NO_CAMERA */		ASTEXT("No camera has been found. The conference will proceed without local video."),
	/* APP_STRINGS_NO_MICROPHONE */		ASTEXT("No microphone has been found. The conference will proceed without local audio input."),
	/* APP_STRINGS_JOIN_INTERNAL_ERROR */		ASTEXT("An internal error has occurred while joining. Please quit VidyoDesktop and sign in again to the VidyoPortal. If the problem persists, please contact your support team."),
	/* APP_STRINGS_NO_SPEAKERS */		ASTEXT("No speakers have been found. The conference will proceed without local audio output."),
	/* APP_STRINGS_COMPLETE_CALL_INTERNAL_ERROR */		ASTEXT("An internal error has occurred while connecting call. Please quit VidyoDesktop and sign in again to the VidyoPortal. If the problem persists, please contact your support team."),
	/* APP_STRINGS_JOIN_ERROR */		ASTEXT("Error while joining conference. Please try to join again."),
	/* APP_STRINGS_CALLEE_DECLINED */		ASTEXT("%s has declined the call"),
	/* APP_STRINGS_LOGGED_IN_ELSEWHERE_ERROR */		ASTEXT("You are logged in elsewhere. Please sign in again on the VidyoPortal."),
	/* APP_STRINGS_NOT_LOGGED_IN_ERROR */		ASTEXT("You are not logged in. Please sign in again on the VidyoPortal."),
	/* APP_STRINGS_IN_CALL_ERROR */		ASTEXT("Already in a call."),
	/* APP_STRINGS_IN_CALL_OR_CONFERENCE_ERROR */		ASTEXT("Already in a call or conference."),
	/* APP_STRINGS_UNEXPECTED_ERROR */		ASTEXT("An unexpected error has occurred. Please quit VidyoDesktop and sign in again to the VidyoPortal. If the problem persists, please contact your support team."),
	/* APP_STRINGS_CALL_INTERNAL_ERROR */		ASTEXT("An internal error has occurred while calling. Please quit VidyoDesktop and sign in again to the VidyoPortal. If the problem persists, please contact your support team."),
	/* APP_STRINGS_SIGNIN_INTERNAL_ERROR */		ASTEXT("An internal error has occurred while signing in. Please quit VidyoDesktop and sign in again to the VidyoPortal.  If the problem persists, please contact your support team."),
	/* APP_STRINGS_ACCEPT_INTERNAL_ERROR */		ASTEXT("An internal error has occurred while answering call. Please quit VidyoDesktop and sign in again to the VidyoPortal. If the problem persists, please contact your support team."),
	/* APP_STRINGS_IGNORE_INTERNAL_ERROR */		ASTEXT("An internal error has occurred while declining call. Please quit VidyoDesktop and sign in again to the VidyoPortal. If the problem persists, please contact your support team."),
	/* APP_STRINGS_RESTART_VIDEO_INTERNAL_ERROR */		ASTEXT("An internal error has occurred while trying to restart video. Please quit VidyoDesktop and sign in again to the VidyoPortal. If the problem persists, please contact your support team."),
	/* APP_STRINGS_LOCK_INTERNAL_ERROR */		ASTEXT("An internal error has occurred while locking conference. Please quit VidyoDesktop and sign in again to the VidyoPortal. If the problem persists, please contact your support team."),
	/* APP_STRINGS_MISSING_VALUE_F_OPTION_ERROR */		ASTEXT("Missing value for -f (log File) option."),
	/* APP_STRINGS_MISSING_VALUE_L_OPTION_ERROR */		ASTEXT("Missing value for -l (Log levels/categories) option."),
	/* APP_STRINGS_MISSING_VALUE_LS_OPTION_ERROR */		ASTEXT("Missing value for -ls (Log Size) option."),
	/* APP_STRINGS_RANGE_LS_OPTION_ERROR */		ASTEXT("Log size must be within the range %d-%d (current value = %d)"),
	/* APP_STRINGS_MISSING_VALUE_CH_OPTION_ERROR */		ASTEXT("Missing value for -ch (max Capture Height) option."),
	/* APP_STRINGS_RANGE_CH_OPTION_ERROR */		ASTEXT("Maximum capture height must be within the range %d-%d (current value = %d)"),
	/* APP_STRINGS_MISSING_VALUE_CW_OPTION_ERROR */		ASTEXT("Missing value for -cw (max Capture Width) option."),
	/* APP_STRINGS_RANGE_CW_OPTION_ERROR */		ASTEXT("Maximum capture width must be within the range %d-%d (current value = %d)"),
	/* APP_STRINGS_MISSING_VALUE_LP_OPTION_ERROR */		ASTEXT("Missing value for -lp (Listening Port) option."),
	/* APP_STRINGS_RANGE_LP_OPTION_ERROR */		ASTEXT("Signaling port must be within the range %d-%d (current value = %d)"),
	/* APP_STRINGS_MISSING_VALUE_MD_OPTION_ERROR */		ASTEXT("Missing value for -md (minidump type) option."),
	/* APP_STRINGS_RANGE_MD_OPTION_ERROR */		ASTEXT("Minidump type must be within the range %d-%d (current value = %d)"),
	/* APP_STRINGS_MISSING_VALUE_P_OPTION_ERROR */		ASTEXT("Missing value for -p (Password) option."),
	/* APP_STRINGS_MISSING_VALUE_S_OPTION_ERROR */		ASTEXT("Missing value for -s (Server) option."),
	/* APP_STRINGS_MISSING_VALUE_U_OPTION_ERROR */		ASTEXT("Missing value for -u (User ID) option."),
	/* APP_STRINGS_DIRECT_X_DISABLED_ERROR */		ASTEXT("Unable to render video. Please upgrade Direct-X and video/graphic drivers to the latest versions and enable Direct-X acceleration using the dxdiag utility."),
	/* APP_STRINGS_NO_DIRECT_X_ERROR */		ASTEXT("Unable to render video. Please upgrade Direct-X and video/graphic drivers to the latest versions and enable Direct-X acceleration using the dxdiag utility."),
	/* APP_STRINGS_NO_MAC_ADDR_ERROR */		ASTEXT("Error with license key or determination of MAC address. Please uninstall and reinstall VidyoDesktop."),
	/* APP_STRINGS_DISCONNECTED_FROM_CONFERENCE */		ASTEXT("Call disconnected by the operator"),
	/* APP_STRINGS_CONNECTION_TO_SERVER_LOST */		ASTEXT("Connection to the VidyoRouter was lost. Please try to join again."),
	/* APP_STRINGS_HEARTBEAT_FAILED */		ASTEXT("Connection to the VidyoRouter failed. Please try to join again."),
	/* APP_STRINGS_DISCONNECTED */		ASTEXT("Disconnected from the conference. Please try to join again."),
	/* APP_STRINGS_BAD_HTTP_RESPONSE */		ASTEXT("Unexpected response received from server"),
	/* APP_STRINGS_407_HTTP_RESPONSE */		ASTEXT("Authorization failed. Check your Web Proxy username and password."),
	/* APP_STRINGS_MISSED_INVITATION_TO_CONFERENCE */		ASTEXT("Missed invitation to conference %s"),
	/* APP_STRINGS_COULDNT_RESOLVE_PROXY */		ASTEXT("Could not resolve Web Proxy address. Please check your network settings."),
	/* APP_STRINGS_QUEUE_INTERNAL_ERROR */		ASTEXT("An internal error has occurred. VidyoDesktop will now exit."),
	/* APP_STRINGS_LICENSE_NOT_VALID */		ASTEXT("A valid VidyoDesktop installation license was not found. Please reinstall VidyoDesktop."),
	/* APP_STRINGS_LOGGED_OUT_BY_SERVER */		ASTEXT("Logged out from VidyoPortal."),
	/* APP_STRINGS_NETWORK_CONNECTIVITY */		ASTEXT("Network connectivity error.  Check your network connectivity and network settings."),
	/* APP_STRINGS_MISSED_CALL */		ASTEXT("Missed call from %s"),
	/* APP_STRINGS_WEB_PROXY_ERROR */		ASTEXT("Error registering license with VidyoPortal. Please check your network and Web Proxy settings."),
	/* APP_STRINGS_REGISTER_LICENSE_COM_ERROR */		ASTEXT("Failed to register installation license with server (error #%03d - %s). Please check your network settings. If the problem persists, please contact your support team."),
	/* APP_STRINGS_REGISTER_LICENSE_OTHER */		ASTEXT("Error registering installation license with server (error #%03d - %s). Please try logging in to VidyoPortal again."),
	/* APP_STRINGS_UD_CHECK_UPDATES_MSG */		ASTEXT("You are currently running the latest software version: %s."),
	/* APP_STRINGS_MAXDESKTOPS_ERROR */		ASTEXT("VidyoDesktop license limit exceeded at server."),
	/* APP_STRINGS_VIDYO_PROXY_CONNECT_ERROR */		ASTEXT("Error connecting with VidyoProxy"),
	ASTEXT("<END>")
};
 

static const unsigned int NUMBER_OF_LANGUAGES = 18;
static const char *OutputStringFileNames[] = 
{ 
	"AppStrings.en",	
	"AppStrings.de",	
	"AppStrings.es",	
	"AppStrings.fr",	
	"AppStrings.it",	
	"AppStrings.ja",	
	"AppStrings.kr",	
	"AppStrings.pt",	
	"AppStrings.zh",	
	"AppStrings.po",	
 	"AppStrings.fi",	
 	"AppStrings.tc",	
 	"AppStrings.th",	
 	"AppStrings.ru",	
 	"AppStrings.tr",	
 	"AppStrings.no",	
 	"AppStrings.sv",	
 	"AppStrings.nl",	
 };

#endif // APP_STRINGS_TABLE_H
