/*
 *  MessageLookup.h
 *  
 *
 *  Created by raz.galili on 3/2/11.
 *  Copyright 2011 Vidyo. All rights reserved.
 *
 */
#if !defined(_MASSAGELOOKUP_H_)
#define _MASSAGELOOKUP_H_

	//all messages lookup
#define MASSAGE_LOOKUP(DO) \
	DO(APP_STRINGS_CHANGES_TO_AUDIO_VIDEO_DEVICES,APP_GUIMESSAGETYPE_INFO ) \
	DO(APP_STRINGS_CANNOT_DETERMINE_LOG_PATH, APP_GUIMESSAGETYPE_WARNING) \
	DO(APP_STRINGS_CANNOT_DETERMINE_INSTALLED_PATH, APP_GUIMESSAGETYPE_WARNING) \
	DO(APP_STRINGS_CANNOT_WRITE_LOG_FILE, APP_GUIMESSAGETYPE_WARNING) \
	DO(APP_STRINGS_INIT_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_INIT_ERROR_VIDYO_SDK_BASE, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_INIT_ERROR_FRAMEWORK_LOG, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_INIT_ERROR_VIDYO_DESKTOP_LOG, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_INIT_ERROR_VIDYOPROXY_LOG, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_INIT_ERROR_SDK_CLIENT, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_INIT_ERROR_CONSTRUCTION_VD_LOGIC, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_INIT_ERROR_START_VD_LOGIC, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_INIT_ERROR_VD_HELPER_CONSTRUCT, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_INIT_ERROR_VD_HELPER_START, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_INIT_ERROR_CONSTRUCTION_STRING_TRANSLATION_TABLE, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_INIT_ERROR_SSE2_CHECK_FAILED, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_TASKBAR_ICON_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_CONF_STATUS_HOTKEY, APP_GUIMESSAGETYPE_WARNING) \
	DO(APP_STRINGS_AUDIO_DEBUG_HOTKEY, APP_GUIMESSAGETYPE_WARNING) \
	DO(APP_STRINGS_LOG_SETTINGS_HOTKEY, APP_GUIMESSAGETYPE_WARNING) \
	DO(APP_STRINGS_APP_SERVER_COMM_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_PROTOCOL_VERSION_ERROR, APP_GUIMESSAGETYPE_FATAL) \
	DO(APP_STRINGS_INVALIDUSER_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_INVALIDMAC_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_USERINCONF_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_INVALIDCONF_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MAXPORTS_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_LOCKEDCONF_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_NOROUTER_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_CONFMAXUSERS_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MAXDESKTOPS_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_OFFLINECALLER_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_OFFLINECALLEE_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_INTERNAL_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_START_VIDEO_INTERNAL_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_START_AUDIO_INTERNAL_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_CONTACT_USER_INTERNAL_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_USER_NO_ANSWER, APP_GUIMESSAGETYPE_INFO) \
	DO(APP_STRINGS_ROUTER_REJECT_JOIN_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_OTHER_PARTY_HANGUP, APP_GUIMESSAGETYPE_INFO) \
	DO(APP_STRINGS_NO_CAMERA, APP_GUIMESSAGETYPE_WARNING) \
	DO(APP_STRINGS_NO_MICROPHONE, APP_GUIMESSAGETYPE_WARNING) \
	DO(APP_STRINGS_JOIN_INTERNAL_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_NO_SPEAKERS, APP_GUIMESSAGETYPE_WARNING) \
	DO(APP_STRINGS_COMPLETE_CALL_INTERNAL_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_JOIN_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MISSED_CALL, APP_GUIMESSAGETYPE_INFO) \
	DO(APP_STRINGS_CALLEE_DECLINED, APP_GUIMESSAGETYPE_INFO) \
	DO(APP_STRINGS_LOGGED_IN_ELSEWHERE_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_NOT_LOGGED_IN_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_IN_CALL_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_IN_CALL_OR_CONFERENCE_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_UNEXPECTED_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_CALL_INTERNAL_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_SIGNIN_INTERNAL_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_ACCEPT_INTERNAL_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_IGNORE_INTERNAL_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_RESTART_VIDEO_INTERNAL_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_LOCK_INTERNAL_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MISSING_VALUE_F_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MISSING_VALUE_L_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MISSING_VALUE_LS_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_RANGE_LS_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MISSING_VALUE_CH_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_RANGE_CH_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MISSING_VALUE_CW_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_RANGE_CW_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MISSING_VALUE_LP_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_RANGE_LP_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MISSING_VALUE_MD_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_RANGE_MD_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MISSING_VALUE_P_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MISSING_VALUE_S_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MISSING_VALUE_U_OPTION_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_DIRECT_X_DISABLED_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_NO_DIRECT_X_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_NO_MAC_ADDR_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_DISCONNECTED_FROM_CONFERENCE, APP_GUIMESSAGETYPE_INFO) \
	DO(APP_STRINGS_CONNECTION_TO_SERVER_LOST, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_HEARTBEAT_FAILED, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_DISCONNECTED, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_BAD_HTTP_RESPONSE, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_407_HTTP_RESPONSE, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MISSED_INVITATION_TO_CONFERENCE, APP_GUIMESSAGETYPE_INFO) \
	DO(APP_STRINGS_VIDYO_PROXY_CONNECT_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_COULDNT_RESOLVE_PROXY, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_QUEUE_INTERNAL_ERROR, APP_GUIMESSAGETYPE_FATAL) \
	DO(APP_STRINGS_LICENSE_NOT_VALID, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_LOGGED_OUT_BY_SERVER, APP_GUIMESSAGETYPE_INFO) \
	DO(APP_STRINGS_NETWORK_CONNECTIVITY, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_MISSED_CALL, APP_GUIMESSAGETYPE_INFO) \
	DO(APP_STRINGS_WEB_PROXY_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_REGISTER_LICENSE_COM_ERROR, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_REGISTER_LICENSE_OTHER, APP_GUIMESSAGETYPE_ERROR) \
	DO(APP_STRINGS_UD_CHECK_UPDATES_MSG, APP_GUIMESSAGETYPE_INFO) 														

#define CURL_ERROR_STRING_LOOKUP(DO) \
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_COULD_NOT_RESOLVE_PROXY,		APP_STRINGS_CURL_ERROR_COULD_NOT_RESOLVE_PROXY) \
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_COULD_NOT_RESOLVE_HOST,		APP_STRINGS_CURL_ERROR_COULD_NOT_RESOLVE_HOST)	\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_COULD_NOT_CONNECT,			APP_STRINGS_CURL_ERROR_COULD_NOT_CONNECT)		\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_REMOTE_ACCESS_DENIED, 		APP_STRINGS_CURL_ERROR_ACCESS_DENIED) 			\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_HTTP_RETURNED_ERROR, 		APP_STRINGS_CURL_ERROR_HTTP_RETURNED_ERROR) 	\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_OPERATION_TIMED_OUT, 		APP_STRINGS_CURL_ERROR_OPERATION_TIMED_OUT) 	\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_TOO_MANY_REDIRECTS, 			APP_STRINGS_CURL_ERROR_TOO_MANY_REDIRECTS) 		\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_GOT_NOTHING, 				APP_STRINGS_CURL_ERROR_GOT_NOTHING) 			\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_SSL_ENGINE_NOT_FOUND, 		APP_STRINGS_CURL_ERROR_GENERIC_SSL_FAILURE) 	\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_SSL_ENGINE_SET_FAILED, 		APP_STRINGS_CURL_ERROR_GENERIC_SSL_FAILURE) 	\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_SSL_CIPHER, 					APP_STRINGS_CURL_ERROR_GENERIC_SSL_FAILURE) 	\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_SSL_CERT_PROBLEM, 			APP_STRINGS_CURL_ERROR_GENERIC_SSL_FAILURE)		\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_SSL_CONNECT_ERROR, 			APP_STRINGS_CURL_ERROR_GENERIC_SSL_FAILURE) 	\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_SSL_ENGINE_INIT_FAILED, 		APP_STRINGS_CURL_ERROR_GENERIC_SSL_FAILURE) 	\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_SSL_ISSUER_ERROR, 			APP_STRINGS_CURL_ERROR_GENERIC_SSL_FAILURE) 	\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_PEER_FAILED_VERIFICATION,	APP_STRINGS_CURL_ERROR_GENERIC_SSL_FAILURE) 	\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_BAD_CONTENT_ENCODING, 		APP_STRINGS_CURL_ERROR_BAD_CONTENT_ENCODING) 	\
	DO(VIDYO_CLIENT_PRIVATE_SOAP_ERROR_FILE_SIZE_EXCEEDED,			APP_STRINGS_CURL_ERROR_FILE_SIZE_EXCEEDED) 		



// All initialization error strings take a single int as parameter passed in event->messageCode[0]
#define INITIALIZATION_FAILURE_MESSAGES(DO)												\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_INIT_ERROR_VIDYO_SDK_BASE)						\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_INIT_ERROR_FRAMEWORK_LOG)							\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_INIT_ERROR_VIDYO_DESKTOP_LOG)						\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_INIT_ERROR_VIDYOPROXY_LOG)						\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_INIT_ERROR_SDK_CLIENT)							\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_INIT_ERROR_CONSTRUCTION_VD_LOGIC)					\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_INIT_ERROR_START_VD_LOGIC)						\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_INIT_ERROR_VD_HELPER_CONSTRUCT)					\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_INIT_ERROR_VD_HELPER_START)						\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_INIT_ERROR_CONSTRUCTION_STRING_TRANSLATION_TABLE)	\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_INIT_ERROR_SSE2_CHECK_FAILED) 

// Licensing failure (based on CURL error messages) */
#define LICENSING_ERRORS(DO)															\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_REGISTER_LICENSE_COM_ERROR)						\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_REGISTER_LICENSE_OTHER)	

// messages of "value out of range" take 3 parameters from event->messageCode[0], 1 and 2
#define VALUE_OUT_OF_RANGE_ERRORS(DO)													\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_MISSING_VALUE_LS_OPTION_ERROR)					\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_MISSING_VALUE_CH_OPTION_ERROR)					\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_MISSING_VALUE_CW_OPTION_ERROR)					\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_MISSING_VALUE_LP_OPTION_ERROR)					\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_MISSING_VALUE_MD_OPTION_ERROR) 

//Call failed messages take as parameter the name of the user passed in  event->messageString as a UTF 8 string
#define CALL_FAILED(DO)																	\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_CALLER_CANCELLED)									\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_CALLEE_DECLINED)									\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_CALL_TIMED_OUT)									\
	DO(VIDYO_CLIENT_USER_MESSAGE_TYPE_INVITATION_TIMED_OUT) 



typedef enum 
{
	APP_GUIMESSAGETYPE_INFO,
	APP_GUIMESSAGETYPE_WARNING,
	APP_GUIMESSAGETYPE_ERROR,
	APP_GUIMESSAGETYPE_FATAL,
} AppGuiMessageType;

#endif // _MASSAGELOOKUP_H_
