//
//	VidyoLocalRenderer_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, LocalRendererViewStyle){
	LOCALRENDERERVIEWSTYLE_Default,
	LOCALRENDERERVIEWSTYLE_Tiles
};
@interface LocalRenderer : NSObject
{
	void* objPtr;
	@public
	NSMutableString* id;
	NSMutableString* name;
}

	-(void) dealloc;
	-(NSString*) GetId;
	-(NSString*) GetName;
	-(BOOL) IsPaused;
	-(void) Pause;
	-(void) Resume;
	-(BOOL) SetMaxStreams:(unsigned int)numStreams;
	-(BOOL) SetPosition:(int)x Y:(int)y Width:(unsigned int)width Height:(unsigned int)height;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
