//
//	VidyoContact_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

@class ContactProperty;
typedef NS_ENUM(NSInteger, ContactPresenceState){
	CONTACTPRESENCESTATE_Available,
	CONTACTPRESENCESTATE_Away,
	CONTACTPRESENCESTATE_DoNotDisturb,
	CONTACTPRESENCESTATE_ExtendedAway,
	CONTACTPRESENCESTATE_InterestedInChat,
	CONTACTPRESENCESTATE_Unavailable
};
typedef NS_ENUM(NSInteger, ContactSubscriptionState){
	CONTACTSUBSCRIPTIONSTATE_AwaitingApproval,
	CONTACTSUBSCRIPTIONSTATE_NotSubscribed,
	CONTACTSUBSCRIPTIONSTATE_Preapproved,
	CONTACTSUBSCRIPTIONSTATE_Subscribed,
	CONTACTSUBSCRIPTIONSTATE_Unavailable
};
@interface Contact : NSObject
{
	@public
	NSMutableArray* emails;
	NSMutableArray* groups;
	NSMutableString* handle;
	NSMutableString* id;
	NSMutableString* name;
	NSMutableString* nickname;
	NSMutableString* photo;
	ContactPresenceState presenceState;
	NSMutableString* presenceStatus;
	ContactSubscriptionState publicationState;
	ContactSubscriptionState subscriptionState;
	NSMutableArray* telephones;
	long timestamp;
}

@end
@interface ContactProperty : NSObject
{
	@public
	NSMutableArray* types;
	NSMutableString* value;
}

@end
