//
//	VidyoRoomInfo_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoChatMessage_Objc.h"
#import "VidyoEndpoint_Objc.h"
@interface RoomInfo : NSObject
{
	@public
	BOOL IsFavorite;
	BOOL IsPublic;
	long creationTime;
	NSMutableString* description;
	NSMutableString* id;
	NSMutableString* language;
	NSMutableArray* messageList;
	NSMutableString* name;
	int numUsers;
	NSMutableArray* ownerList;
	RoomType type;
	NSMutableArray* userList;
}

@end
