//
//	VidyoLocalWindowShare_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoLocalRenderer_Objc.h"
#import "VidyoRemoteRenderer_Objc.h"
typedef NS_ENUM(NSInteger, LocalWindowShareState){
	LOCALWINDOWSHARESTATE_Closed,
	LOCALWINDOWSHARESTATE_Minimized,
	LOCALWINDOWSHARESTATE_MiscError,
	LOCALWINDOWSHARESTATE_NotVisible,
	LOCALWINDOWSHARESTATE_Ok
};
@protocol IGetApplicationIconFrameDataUriAsync

	-(void) OnApplicationIconDataUriComplete:(NSString*)icon;
@end
@protocol IGetPreviewFrameDataUriAsync

	-(void) OnPreviewDataUriComplete:(NSString*)videoFrame State:(LocalWindowShareState)state;
@end
@interface LocalWindowShare : NSObject
{
	void* objPtr;
	@public
	NSMutableString* applicationName;
	NSMutableString* id;
	NSMutableString* name;
	id<IGetApplicationIconFrameDataUriAsync> getApplicationIconFrameDataUriAsync;
	id<IGetPreviewFrameDataUriAsync> getPreviewFrameDataUriAsync;
}

	-(void) dealloc;
	-(long) AddToLocalRenderer:(LocalRenderer*)renderer;
	-(BOOL) AddToRemoteRenderer:(RemoteRenderer*)remoteRenderer;
	-(void) ClearConstraints;
	-(BOOL) GetApplicationIconFrameDataUriAsync:(size_t)maxWidth MaxHeight:(size_t)maxHeight GetApplicationIconFrameDataUriAsync:(id<IGetApplicationIconFrameDataUriAsync>)getApplicationIconFrameDataUriAsync;
	-(NSString*) GetApplicationName;
	-(NSString*) GetId;
	-(NSString*) GetName;
	-(BOOL) GetPreviewFrameDataUriAsync:(size_t)maxWidth MaxHeight:(size_t)maxHeight GetPreviewFrameDataUriAsync:(id<IGetPreviewFrameDataUriAsync>)getPreviewFrameDataUriAsync;
	-(unsigned int) GetProcessId;
	-(BOOL) IsApplicationNameSet;
	-(BOOL) IsNameSet;
	-(BOOL) RemoveFromLocalRenderer:(LocalRenderer*)renderer;
	-(BOOL) RemoveFromRemoteRenderer:(RemoteRenderer*)remoteRenderer;
	-(BOOL) SetBoundsConstraints:(long)maxFrameInterval MinFrameInterval:(long)minFrameInterval MaxWidth:(unsigned int)maxWidth MinWidth:(unsigned int)minWidth MaxHeight:(unsigned int)maxHeight MinHeight:(unsigned int)minHeight;
	-(BOOL) SetCapability:(long)frameInterval ShowCursor:(BOOL)showCursor RedactOccludedAreas:(BOOL)redactOccludedAreas;
	-(BOOL) SetDiscrerteConstraints:(long)maxFrameInterval MinFrameInterval:(long)minFrameInterval Width:(unsigned int)width Height:(unsigned int)height ScaleFactor:(float)scaleFactor;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
