//
//	VidyoLocalMicrophone_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoDevice_Objc.h"
#import "VidyoLocalSpeaker_Objc.h"
#import "VidyoRemoteSpeaker_Objc.h"
@interface LocalMicrophone : NSObject
{
	void* objPtr;
	@public
	NSMutableString* id;
	NSMutableString* name;
}

	-(void) dealloc;
	-(BOOL) AddToLocalSpeaker:(LocalSpeaker*)speaker;
	-(BOOL) AddToRemoteSpeaker:(RemoteSpeaker*)remoteSpeaker;
	-(BOOL) DisableDebugRecording;
	-(BOOL) EnableDebugRecording:(NSString*)dir;
	-(BOOL) GetAutoGain;
	-(NSString*) GetId;
	-(NSString*) GetName;
	-(DeviceAudioSignalType) GetSignalType;
	-(BOOL) GetVoiceProcessing;
	-(unsigned int) GetVolume;
	-(void) HideDebugDialog;
	-(BOOL) IsDebugRecordingEnabled;
	-(BOOL) IsPaused;
	-(void) Pause;
	-(void) PlayTone:(char)dtmfTone;
	-(BOOL) RemoveFromLocalSpeaker:(LocalSpeaker*)speaker;
	-(BOOL) RemoveFromRemoteSpeaker:(RemoteSpeaker*)remoteSpeaker;
	-(void) Resume;
	-(BOOL) SetAutoGain:(BOOL)autoGain;
	-(BOOL) SetEchoCancellation:(LocalSpeaker*)speaker IsEnable:(BOOL)isEnable;
	-(BOOL) SetSignalType:(DeviceAudioSignalType)signalType;
	-(BOOL) SetVoiceProcessing:(BOOL)voiceProcessing;
	-(void) SetVolume:(unsigned int)volumePercent;
	-(void) ShowDebugDialog;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
