//
//	VidyoNetworkInterface_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, NetworkInterfaceFamily){
	NETWORKINTERFACEFAMILY_IPV4,
	NETWORKINTERFACEFAMILY_IPV6,
	NETWORKINTERFACEFAMILY_Unspecified
};
typedef NS_ENUM(NSInteger, NetworkInterfaceState){
	NETWORKINTERFACESTATE_Down,
	NETWORKINTERFACESTATE_Unknown,
	NETWORKINTERFACESTATE_Up
};
typedef NS_ENUM(NSInteger, NetworkInterfaceTransportType){
	NETWORKINTERFACETRANSPORTTYPE_Data,
	NETWORKINTERFACETRANSPORTTYPE_Media,
	NETWORKINTERFACETRANSPORTTYPE_Signaling
};
typedef NS_ENUM(NSInteger, NetworkInterfaceType){
	NETWORKINTERFACETYPE_Loopback,
	NETWORKINTERFACETYPE_NotApplicable,
	NETWORKINTERFACETYPE_Other,
	NETWORKINTERFACETYPE_Tunneled,
	NETWORKINTERFACETYPE_WiFi,
	NETWORKINTERFACETYPE_Wired,
	NETWORKINTERFACETYPE_Wwan
};
@interface NetworkInterface : NSObject
{
	void* objPtr;
	@public
	NSMutableString* address;
	NetworkInterfaceFamily family;
	NSMutableString* name;
	NetworkInterfaceState state;
	NetworkInterfaceType type;
}

	-(void) dealloc;
	-(NSString*) GetAddress;
	-(NetworkInterfaceFamily) GetFamily;
	-(NSString*) GetName;
	-(NetworkInterfaceState) GetState;
	-(NetworkInterfaceType) GetType;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
