//
//	VidyoRemoteCamera_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoLocalRenderer_Objc.h"
typedef NS_ENUM(NSInteger, RemoteCameraMode){
	REMOTECAMERAMODE_Dynamic,
	REMOTECAMERAMODE_Static
};
typedef NS_ENUM(NSInteger, RemoteCameraPosition){
	REMOTECAMERAPOSITION_Back,
	REMOTECAMERAPOSITION_Front,
	REMOTECAMERAPOSITION_Unknown
};
@interface RemoteCamera : NSObject
{
	void* objPtr;
	@public
	NSMutableString* id;
	NSMutableString* name;
}

	-(void) dealloc;
	-(long) AddToLocalRenderer:(LocalRenderer*)localRenderer Mode:(RemoteCameraMode)mode;
	-(BOOL) ControlPTZ:(int)pan Tilt:(int)tilt Zoom:(int)zoom;
	-(NSString*) GetId;
	-(long) GetLocalRenderingStreamId:(int)index;
	-(NSString*) GetName;
	-(RemoteCameraPosition) GetPosition;
	-(BOOL) IsControllable;
	-(BOOL) RemoveFromLocalRenderer:(LocalRenderer*)localRenderer;
	-(BOOL) SetPositionInLocalRenderer:(LocalRenderer*)localRenderer X:(int)x Y:(int)y Width:(unsigned int)width Height:(unsigned int)height FrameInterval:(long)frameInterval;
	-(BOOL) ShowCameraControl:(BOOL)show;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
