//
//	VidyoGateway_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, GatewayDisconnectReason){
	GATEWAYDISCONNECTREASON_ConnectionLost,
	GATEWAYDISCONNECTREASON_ConnectionTimeout,
	GATEWAYDISCONNECTREASON_Disconnected,
	GATEWAYDISCONNECTREASON_MiscError,
	GATEWAYDISCONNECTREASON_MiscLocalError,
	GATEWAYDISCONNECTREASON_MiscRemoteError,
	GATEWAYDISCONNECTREASON_NoResponse,
	GATEWAYDISCONNECTREASON_Terminated
};
typedef NS_ENUM(NSInteger, GatewayFailReason){
	GATEWAYFAILREASON_Banned,
	GATEWAYFAILREASON_ConnectionFailed,
	GATEWAYFAILREASON_ConnectionLost,
	GATEWAYFAILREASON_ConnectionTimeout,
	GATEWAYFAILREASON_InvalidResourceId,
	GATEWAYFAILREASON_InvalidToken,
	GATEWAYFAILREASON_MediaFailed,
	GATEWAYFAILREASON_MediaNotEnabled,
	GATEWAYFAILREASON_MiscError,
	GATEWAYFAILREASON_MiscLocalError,
	GATEWAYFAILREASON_MiscRemoteError,
	GATEWAYFAILREASON_NoResponse,
	GATEWAYFAILREASON_NoResponseFromResource,
	GATEWAYFAILREASON_NotMember,
	GATEWAYFAILREASON_ResourceFull,
	GATEWAYFAILREASON_Terminated,
	GATEWAYFAILREASON_UnableToCreateResource
};
typedef NS_ENUM(NSInteger, GatewayState){
	GATEWAYSTATE_Connected,
	GATEWAYSTATE_ConnectingToResource,
	GATEWAYSTATE_EnablingMedia,
	GATEWAYSTATE_EstablishingConnection,
	GATEWAYSTATE_FindingResource,
	GATEWAYSTATE_Idle
};
@protocol IConnect

	-(void) OnSuccess;
	-(void) OnFailure:(GatewayFailReason)reason;
	-(void) OnDisconnected:(GatewayDisconnectReason)reason;
@end
@interface Gateway : NSObject
{
	void* objPtr;
	@public
	id<IConnect> connect;
}

	-(void) dealloc;
	-(BOOL) Connect:(const char*)host Token:(const char*)token DisplayName:(const char*)displayName ResourceId:(const char*)resourceId Connect:(id<IConnect>)connect;
	-(void) Disconnect;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
