//
//	VidyoRemoteRenderer_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

@interface RemoteRenderer : NSObject
{
	void* objPtr;
	@public
	NSMutableString* id;
	NSMutableString* name;
}

	-(void) dealloc;
	-(NSString*) GetId;
	-(NSString*) GetName;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
