//
//	VidyoChatMessage_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, ChatMessageSenderType){
	CHATMESSAGESENDERTYPE_None,
	CHATMESSAGESENDERTYPE_Room,
	CHATMESSAGESENDERTYPE_System,
	CHATMESSAGESENDERTYPE_User
};
typedef NS_ENUM(NSInteger, ChatMessageType){
	CHATMESSAGETYPE_Chat,
	CHATMESSAGETYPE_MediaStart,
	CHATMESSAGETYPE_MediaStop
};
typedef NS_ENUM(NSInteger, ChatMessageTypingIndication){
	CHATMESSAGETYPINGINDICATION_Active,
	CHATMESSAGETYPINGINDICATION_Composing,
	CHATMESSAGETYPINGINDICATION_Gone,
	CHATMESSAGETYPINGINDICATION_Inactive,
	CHATMESSAGETYPINGINDICATION_None,
	CHATMESSAGETYPINGINDICATION_Paused
};
@interface ChatMessage : NSObject
{
	@public
	NSMutableString* body;
	long long id;
	ChatMessageSenderType senderType;
	long timestamp;
	ChatMessageType type;
	NSMutableString* userId;
}

@end
