//
//	VidyoContactInfo_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

@class ContactInfoProperty;
@interface ContactInfo : NSObject
{
	@public
	NSMutableArray* emails;
	NSMutableArray* groups;
	NSMutableString* handle;
	NSMutableString* id;
	NSMutableString* name;
	NSMutableString* nickname;
	NSMutableString* photo;
	NSMutableArray* telephones;
	long timestamp;
}

@end
@interface ContactInfoProperty : NSObject
{
	@public
	NSMutableArray* types;
	NSMutableString* value;
}

@end
