//
//	VidyoDevice_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, DeviceAudioSignalType){
	DEVICEAUDIOSIGNALTYPE_Unprocessed,
	DEVICEAUDIOSIGNALTYPE_Voice
};
typedef NS_ENUM(NSInteger, DeviceState){
	DEVICESTATE_Added,
	DEVICESTATE_ConfigureError,
	DEVICESTATE_ConfigureSuccess,
	DEVICESTATE_Controllable,
	DEVICESTATE_DefaultChanged,
	DEVICESTATE_Error,
	DEVICESTATE_NotControllable,
	DEVICESTATE_Paused,
	DEVICESTATE_Removed,
	DEVICESTATE_Resumed,
	DEVICESTATE_Started,
	DEVICESTATE_Stopped,
	DEVICESTATE_Suspended,
	DEVICESTATE_Unsuspended
};
typedef NS_ENUM(NSInteger, DeviceType){
	DEVICETYPE_LocalCamera,
	DEVICETYPE_LocalMicrophone,
	DEVICETYPE_LocalMonitor,
	DEVICETYPE_LocalRenderer,
	DEVICETYPE_LocalSpeaker,
	DEVICETYPE_LocalWindowShare,
	DEVICETYPE_RemoteCamera,
	DEVICETYPE_RemoteMicrophone,
	DEVICETYPE_RemoteRenderer,
	DEVICETYPE_RemoteSpeaker,
	DEVICETYPE_RemoteWindowShare
};
@interface Device : NSObject
{
	void* objPtr;
	@public
	NSMutableString* id;
	NSMutableString* name;
	DeviceType type;
}

	-(void) dealloc;
	-(BOOL) DerivedEqual;
	-(NSString*) GetId;
	-(NSString*) GetName;
	-(DeviceType) GetType;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
