//
//	VidyoMeetingAttendee_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, AttendeeParticipationRole){
	ATTENDEEPARTICIPATIONROLE_Chair,
	ATTENDEEPARTICIPATIONROLE_Informational,
	ATTENDEEPARTICIPATIONROLE_Optional,
	ATTENDEEPARTICIPATIONROLE_Required
};
typedef NS_ENUM(NSInteger, AttendeeParticipationStatus){
	ATTENDEEPARTICIPATIONSTATUS_Accepted,
	ATTENDEEPARTICIPATIONSTATUS_Completed,
	ATTENDEEPARTICIPATIONSTATUS_Declined,
	ATTENDEEPARTICIPATIONSTATUS_Delegated,
	ATTENDEEPARTICIPATIONSTATUS_InProcess,
	ATTENDEEPARTICIPATIONSTATUS_NeedsAction,
	ATTENDEEPARTICIPATIONSTATUS_None,
	ATTENDEEPARTICIPATIONSTATUS_Organized,
	ATTENDEEPARTICIPATIONSTATUS_Tentative
};
@interface MeetingAttendee : NSObject
{
	@public
	NSMutableString* email;
	NSMutableString* name;
	AttendeeParticipationRole role;
	AttendeeParticipationStatus status;
}

@end
