//
//	VidyoFormField_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, FormFieldType){
	FORMFIELDTYPE_Checkbox,
	FORMFIELDTYPE_Password,
	FORMFIELDTYPE_Radio,
	FORMFIELDTYPE_Select,
	FORMFIELDTYPE_Text,
	FORMFIELDTYPE_TextArea
};
