//
//	VidyoMeeting_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoMeetingAttendee_Objc.h"
@class Meeting;
typedef NS_ENUM(NSInteger, MeetingActionResult){
	MEETINGACTIONRESULT_MiscLocalError,
	MEETINGACTIONRESULT_MiscRemoteError,
	MEETINGACTIONRESULT_NoResponse,
	MEETINGACTIONRESULT_OK,
	MEETINGACTIONRESULT_RemovedByLocalUser,
	MEETINGACTIONRESULT_RemovedByRemoteUser,
	MEETINGACTIONRESULT_Unauthorized
};
typedef NS_ENUM(NSInteger, MeetingType){
	MEETINGTYPE_Standard,
	MEETINGTYPE_Vidyo
};
@protocol IMeetingFeedback
@optional

	-(void) MeetingAttendeeAdded:(Meeting*)meeting Attendee:(MeetingAttendee*)attendee;
	-(void) MeetingAttendeeRemoved:(Meeting*)meeting Attendee:(MeetingAttendee*)attendee;
@end
@interface MeetingFeedback : NSObject<IMeetingFeedback>
{
	void* objPtr;
}
	-(id) init;
	-(void) dealloc;
	-(void*)GetObjectPtr;
@end
@interface Meeting : NSObject
{
	void* objPtr;
	@public
	NSMutableString* body;
	NSMutableString* endDateTime;
	NSMutableString* id;
	NSMutableString* location;
	NSMutableString* ownerEmail;
	NSMutableString* ownerName;
	NSMutableString* startDateTime;
	NSMutableString* subject;
	MeetingType type;
	NSMutableString* vidyoMeetingRoomId;
}

	-(void) dealloc;
	-(BOOL) AddAttendee:(MeetingAttendee*)a;
	-(BOOL) GetAttendees:(NSMutableArray*)a;
	-(BOOL) GetAttendeesByRole:(NSMutableArray*)a R:(AttendeeParticipationRole)r;
	-(NSString*) GetBody;
	-(NSString*) GetEndDateTime;
	-(NSString*) GetId;
	-(NSString*) GetLocation;
	-(NSString*) GetOwnerEmail;
	-(NSString*) GetOwnerName;
	-(NSString*) GetStartDateTime;
	-(NSString*) GetSubject;
	-(MeetingType) GetType;
	-(NSString*) GetVidyoMeetingRoomId;
	-(BOOL) RemoveAttendee:(MeetingAttendee*)a;
	-(BOOL) RespondToInvite:(MeetingAttendee*)a S:(AttendeeParticipationStatus)s;
	-(NSString*) RetrieveBody;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
