//
//	VidyoVirtualShareManager_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoDevice_Objc.h"
#import "VidyoEndpoint_Objc.h"
#import "VidyoLocalMonitor_Objc.h"
#import "VidyoLocalWindowShare_Objc.h"
@interface VirtualShareManager : NSObject
{
	void* objPtr;
}

	-(void) dealloc;
	-(BOOL) LocalMonitorEvent:(Endpoint*)endpoint Monitor:(LocalMonitor*)monitor State:(DeviceState)state;
	-(BOOL) LocalWindowShareEvent:(Endpoint*)endpoint WindowShare:(LocalWindowShare*)windowShare State:(DeviceState)state;
	-(BOOL) MediaFailedEvent:(Endpoint*)endpoint;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
