//
//	VidyoRemoteMicrophone_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoDevice_Objc.h"
#import "VidyoLocalSpeaker_Objc.h"
typedef NS_ENUM(NSInteger, RemoteMicrophoneMode){
	REMOTEMICROPHONEMODE_Dynamic,
	REMOTEMICROPHONEMODE_Static
};
@interface RemoteMicrophone : NSObject
{
	void* objPtr;
	@public
	NSMutableString* id;
	NSMutableString* name;
	DeviceAudioSignalType signalType;
}

	-(void) dealloc;
	-(BOOL) AddToLocalSpeaker:(LocalSpeaker*)speaker Mode:(RemoteMicrophoneMode)mode;
	-(NSString*) GetId;
	-(NSString*) GetName;
	-(DeviceAudioSignalType) GetSignalType;
	-(BOOL) RemoveFromLocalSpeaker:(LocalSpeaker*)speaker;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
