//
//	VidyoVideoCapability_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoMediaFormats_Objc.h"
@class TimeRange;
@class VideoFrameIntervalRange;
@interface VideoCapability : NSObject
{
	@public
	size_t height;
	NSMutableArray* ranges;
	size_t width;
}

@end
@interface VideoFrameIntervalRange : NSObject
{
	@public
	NSMutableArray* formats;
	TimeRange* range;
	long step;
}

@end
@interface TimeRange : NSObject
{
	@public
	long begin;
	long end;
}

@end
