//
//	VidyoLocalCamera_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoLocalRenderer_Objc.h"
#import "VidyoRemoteRenderer_Objc.h"
#import "VidyoVideoCapability_Objc.h"
typedef NS_ENUM(NSInteger, LocalCameraPosition){
	LOCALCAMERAPOSITION_Back,
	LOCALCAMERAPOSITION_Front,
	LOCALCAMERAPOSITION_Unknown
};
@interface LocalCamera : NSObject
{
	void* objPtr;
	@public
	NSMutableString* id;
	NSMutableString* name;
}

	-(void) dealloc;
	-(long) AddToLocalRenderer:(LocalRenderer*)localRenderer;
	-(BOOL) AddToRemoteRenderer:(RemoteRenderer*)remoteRenderer;
	-(BOOL) AllowRemoteCameraControl:(BOOL)allow;
	-(BOOL) ControlPTZ:(int)pan Tilt:(int)tilt Zoom:(int)zoom;
	-(NSString*) GetId;
	-(NSString*) GetName;
	-(LocalCameraPosition) GetPosition;
	-(NSString*) GetPreviewLabel;
	-(BOOL) GetVideoCapabilities:(NSMutableArray*)capabilities;
	-(BOOL) IsPaused;
	-(BOOL) IsSuspended;
	-(BOOL) RemoveFromLocalRenderer:(LocalRenderer*)localRenderer;
	-(BOOL) RemoveFromRemoteRenderer:(RemoteRenderer*)remoteRenderer;
	-(void) Resume;
	-(BOOL) SetAspectRatioConstraint:(unsigned int)aspectRatioWidth AspectRatioHeight:(unsigned int)aspectRatioHeight;
	-(BOOL) SetBoundsConstraint:(unsigned int)minWidth MinHeight:(unsigned int)minHeight MaxWidth:(unsigned int)maxWidth MaxHeight:(unsigned int)maxHeight MaxFrameInterval:(long)maxFrameInterval MinFrameInterval:(long)minFrameInterval AspectRatioWidth:(unsigned int)aspectRatioWidth AspectRatioHeight:(unsigned int)aspectRatioHeight TemporalSpatialTradeOff:(unsigned int)temporalSpatialTradeOff;
	-(BOOL) SetCapabilitiesConstraint:(NSMutableArray*)capabilities TemporalSpatialTradeOff:(unsigned int)temporalSpatialTradeOff;
	-(BOOL) SetConstraints:(unsigned int)minWidth MinHeight:(unsigned int)minHeight MaxWidth:(unsigned int)maxWidth MaxHeight:(unsigned int)maxHeight MaxFrameInterval:(unsigned int)maxFrameInterval MinFrameInterval:(unsigned int)minFrameInterval AspectRatioWidth:(unsigned int)aspectRatioWidth AspectRatioHeight:(unsigned int)aspectRatioHeight TemporalSpatialTradeOff:(unsigned int)temporalSpatialTradeOff Capabilities:(NSMutableArray*)capabilities;
	-(BOOL) SetMaxConstraint:(unsigned int)width Height:(unsigned int)height FrameInterval:(long)frameInterval;
	-(BOOL) SetPositionInLocalRenderer:(LocalRenderer*)localRenderer X:(int)x Y:(int)y Width:(unsigned int)width Height:(unsigned int)height FrameInterval:(long)frameInterval;
	-(BOOL) SetPreviewLabel:(NSString*)previewLabel;
	-(BOOL) ShowCameraControl:(BOOL)show;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
