//
//	VidyoLogRecord_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, LogLevel){
	LOGLEVEL_DEBUG,
	LOGLEVEL_ENTER,
	LOGLEVEL_ERROR,
	LOGLEVEL_FATAL,
	LOGLEVEL_INFO,
	LOGLEVEL_INVALID,
	LOGLEVEL_LEAVE,
	LOGLEVEL_RECEIVED,
	LOGLEVEL_SENT,
	LOGLEVEL_WARNING
};
@interface LogRecord : NSObject
{
	@public
	size_t categoryName;
	long eventTime;
	const char * file;
	const char * functionName;
	LogLevel level;
	int line;
	const char * message;
	const char* name;
	const char * threadName;
}

@end
