//
//	VidyoVirtualDeviceManager_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoDevice_Objc.h"
#import "VidyoEndpoint_Objc.h"
#import "VidyoLocalCamera_Objc.h"
#import "VidyoLocalMicrophone_Objc.h"
#import "VidyoLocalSpeaker_Objc.h"
@interface VirtualDeviceManager : NSObject
{
	void* objPtr;
}

	-(void) dealloc;
	-(BOOL) LocalCameraEvent:(Endpoint*)endpoint Camera:(LocalCamera*)camera State:(DeviceState)state;
	-(BOOL) LocalMicrophoneEvent:(Endpoint*)endpoint Microphone:(LocalMicrophone*)microphone State:(DeviceState)state;
	-(BOOL) LocalSpeakerEvent:(Endpoint*)endpoint Speaker:(LocalSpeaker*)speaker State:(DeviceState)state;
	-(BOOL) MediaFailedEvent:(Endpoint*)endpoint;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
