//
//	VidyoParticipant_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoContact_Objc.h"
@interface Participant : NSObject
{
	void* objPtr;
	@public
	NSMutableString* id;
	NSMutableString* name;
	NSMutableString* userId;
}

	-(void) dealloc;
	-(Contact*) GetContact:(Contact*)contact;
	-(NSString*) GetId;
	-(NSString*) GetName;
	-(NSString*) GetUserId;
	-(BOOL) IsHidden;
	-(BOOL) IsLocal;
	-(BOOL) IsRecording;
	-(BOOL) IsSelectable;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
