//
//	VidyoLocalSpeaker_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

@interface LocalSpeaker : NSObject
{
	void* objPtr;
	@public
	NSMutableString* id;
	NSMutableString* name;
}

	-(void) dealloc;
	-(NSString*) GetId;
	-(NSString*) GetName;
	-(unsigned int) GetVolume;
	-(BOOL) IsPaused;
	-(void) Pause;
	-(void) PlayTone:(char)dtmfTone;
	-(void) Resume;
	-(void) SetVolume:(unsigned int)volumePercent;
	-(void) StopSound;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
