//
//	VidyoLocalMonitor_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoLocalRenderer_Objc.h"
#import "VidyoLocalWindowShare_Objc.h"
#import "VidyoRemoteRenderer_Objc.h"
typedef NS_ENUM(NSInteger, LocalMonitorState){
	LOCALMONITORSTATE_MiscError,
	LOCALMONITORSTATE_NotVisible,
	LOCALMONITORSTATE_Ok
};
@protocol IGetPreviewFrameDataUriAsync

	-(void) OnPreviewDataUriComplete:(NSString*)videoFrame State:(LocalMonitorState)state;
@end
@interface LocalMonitor : NSObject
{
	void* objPtr;
	@public
	NSMutableString* id;
	NSMutableString* name;
	id<IGetPreviewFrameDataUriAsync> getPreviewFrameDataUriAsync;
}

	-(void) dealloc;
	-(long) AddToLocalRenderer:(LocalRenderer*)renderer;
	-(BOOL) AddToRemoteRenderer:(RemoteRenderer*)remoteRenderer;
	-(void) ClearConstraints;
	-(NSString*) GetId;
	-(NSString*) GetName;
	-(LocalMonitorState) GetPreviewFrameDataUri:(size_t)maxWidth MaxHeight:(size_t)maxHeight VideoFrame:(NSMutableString*)videoFrame;
	-(BOOL) GetPreviewFrameDataUriAsync:(size_t)maxWidth MaxHeight:(size_t)maxHeight GetPreviewFrameDataUriAsync:(id<IGetPreviewFrameDataUriAsync>)getPreviewFrameDataUriAsync;
	-(void) PrecludeWindow:(LocalWindowShare*)w;
	-(BOOL) RemoveFromLocalRenderer:(LocalRenderer*)renderer;
	-(BOOL) RemoveFromRemoteRenderer:(RemoteRenderer*)remoteRenderer;
	-(BOOL) SetBoundsConstraints:(long)maxFrameInterval MinFrameInterval:(long)minFrameInterval MaxWidth:(unsigned int)maxWidth MinWidth:(unsigned int)minWidth MaxHeight:(unsigned int)maxHeight MinHeight:(unsigned int)minHeight;
	-(BOOL) SetCaptureInterval:(long)frameInterval;
	-(BOOL) SetDiscrerteConstraints:(long)maxFrameInterval MinFrameInterval:(long)minFrameInterval Width:(unsigned int)width Height:(unsigned int)height ScaleFactor:(float)scaleFactor;
	-(id) initWithObject:(void*)rPtr;
	-(void*)GetObjectPtr;
@end
